services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3004"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge