# Configuración minimalista para Railway con Node.js
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# Configuración de healthcheck - valores más permisivos para diagnóstico
healthcheckPath = "/"
healthcheckTimeout = 15
restartPolicyType = "ALWAYS"
healthcheckInterval = 15

# Variables de entorno esenciales para la aplicación React
[deploy.envs]
NODE_ENV = "production"
PORT = "8080"
VITE_SUPABASE_URL = "https://ogzxogjatdmfisiyapdq.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nenhvZ2phdGRtZmlzaXlhcGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTA2NDYsImV4cCI6MjA1NTU2NjY0Nn0.RvgFS7mkmwl5_kVujksTUlZh49wg0L8zMoemXD6D1F4"
VITE_APP_NAME = "Broky-Front"
VITE_APP_DESCRIPTION = "Frontend of Broky"
VITE_APP_VERSION = "1.0.0"
VITE_API_TIMEOUT = "30000"
VITE_API_RETRY_ATTEMPTS = "3"
VITE_ENABLE_DARK_MODE = "true"
VITE_ENABLE_NOTIFICATIONS = "true"

# Puerto interno para el servicio
[[services]]
internal_port = 8080
protocol = "tcp"