[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
VITE_SUPABASE_URL = "${SUPABASE_URL}"
VITE_SUPABASE_ANON_KEY = "${SUPABASE_ANON_KEY}"
VITE_APP_NAME = "SaaS Platform"
VITE_APP_DESCRIPTION = "Panel de Administración"
VITE_APP_VERSION = "1.0.0"
VITE_API_TIMEOUT = "30000"
VITE_API_RETRY_ATTEMPTS = "3"
VITE_ENABLE_DARK_MODE = "true"
VITE_ENABLE_NOTIFICATIONS = "true"

[[services]]
internal_port = 3004
protocol = "tcp"